export enum CancellationReason {
    BY_NOT_WITHDRAWN_VEHICLE = 'BY_NOT_WITHDRAWN_VEHICLE',
    VEHICLE_UNAVAILABLE = 'VEHICLE_UNAVAILABLE',
    BACKOFFICE_BY_OPERATOR = 'BACKOFFICE_BY_OPERATOR',
    BY_DRIVER = 'BY_DRIVER',
}
